# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem 'sinatra', require: 'sinatra/base'
gem 'slim'
gem 'recursive-open-struct'
gem 'faraday'
group :test do
  gem 'cucumber'
end
gem 'capybara'
gem 'selenium-webdriver'